# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      - name: Add dummy genologicsrc
        run: |
          echo "[genologics]\nBASEURI=https://fancy.server\nUSERNAME=username\nPASSWORD=pass\n" > ~/.genologicsrc
          cat ~/.genologicsrc
      - name: Install dependencies
        run: |
          ./clarity-ext-scripts/setup.sh
      - name: Test with pytest
        run: |
          pip install pytest
          pytest ./clarity-ext-scripts/tests
          pytest ./sminet-client/tests

